FROM node:20-alpine AS builder
WORKDIR /app

RUN corepack enable

ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

COPY package.json ./
RUN pnpm install --no-frozen-lockfile

COPY . .

RUN pnpm run build

FROM node:20-alpine
WORKDIR /app

RUN corepack enable

COPY --from=builder /app/build ./build
COPY --from=builder /app/package.json ./
COPY --from=builder /app/node_modules ./node_modules

EXPOSE 3000

ENV PORT=3000
ENV HOST=0.0.0.0

CMD ["node", "build"]
